name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.6

  send_support_email:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  package_rename: ^1.1.0

flutter:
  uses-material-design: true

# flutter pub run package_rename:set
package_rename_config:
  android:
    app_name: send_support_email_example
    package_name: com.example.send_support_email_example
#    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name

  ios:
    app_name: send_support_email_example
    bundle_name: send_support_email_example
    package_name: com.example.send_support_email_example

  macos:
    app_name: send_support_email_example
    package_name: com.example.send_support_email_example
    copyright_notice: Copyright ©️ 2023 send_support_email_example. All rights reserved.

  windows:
    app_name: send_support_email_example
    organization: send_support_email_example
    copyright_notice: Copyright ©️ 2023 send_support_email_example. All rights reserved.
    exe_name: send_support_email_example

  linux:
    app_name: send_support_email_example
    package_name: com.example.send_support_email_example
    exe_name: send_support_email_example

  web:
    app_name: send_support_email_example
    description: A new Flutter project.
