name: send_support_email
description: A new Flutter package project.
version: 1.1.0
repository: https://github.com/albemala/send_support_email

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:
